### ISSUE TITLE
some components do not have direct variables to style

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-ui-components#15]
## Context

Some components do not have direct variables to style, resulting in a scenario where other color systems like the one in vscode which works with foreground & background can't be used easily.

See `.tag--neutral`

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/7cfec67d-c1a9-4c3f-b362-e1ea206dab5a/e2d30df8-09df-42ad-a310-011927c75af0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC83Y2ZlYzY3ZC1jMWE5LTRjM2YtYjM2Mi1lMWVhMjA2ZGFiNWEvZTJkMzBkZjgtMDlkZi00MmFkLWEzMTAtMDExOTI3Yzc1YWYwIiwiaWF0IjoxNzEyNTc4NjA2LCJleHAiOjMzMjgzMTM4NjA2fQ.FdZvVv3PDXva_GJIwp6K5P40uztI9eh367xpiSSP_ns " alt="Bildschirmfoto 2024-04-08 um 12.44.21.png" width="1343" height="573" />

See `.example`

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/a28b7711-1566-43e4-b558-4d9c5bfeb3da/1fded05d-7174-4f4e-b305-a4c0137fe09d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9hMjhiNzcxMS0xNTY2LTQzZTQtYjU1OC00ZDljNWJmZWIzZGEvMWZkZWQwNWQtNzE3NC00ZjRlLWIzMDUtYTRjMDEzN2ZlMDlkIiwiaWF0IjoxNzEyNTc4NjA2LCJleHAiOjMzMjgzMTM4NjA2fQ.GM5hGnUwvUF2Ee8Qmvgtj47MKli_-zeMb8ph_ILGEhM " alt="Bildschirmfoto 2024-04-08 um 12.42.31.png" width="1345" height="586" />

## Proposal

Watch the LOOM 📹
[https://www.loom.com/share/d423e177fd09415ebb135b0686501b10](https://www.loom.com/share/d423e177fd09415ebb135b0686501b10)

**Comment by felixhaeberle** [comment]
> I wanted to let you run into this problem to see which properties we really need.

Thanks 😂

**Comment by felixhaeberle** [comment]
Color values can be defined in the RGB color model with an alpha channel for transparency. As format, the following hexadecimal notations are supported: `#RGB`, `#RGBA`, `#RRGGBB` and `#RRGGBBAA`. R (red), G (green), B (blue), and A (alpha) are hexadecimal characters (0-9, a-f or A-F). The three-digit notation (`#RGB`) is a shorter version of the six-digit form (`#RRGGBB`) and the four-digit RGB notation (`#RGBA`) is a shorter version of the eight-digit form (`#RRGGBBAA`). For example `#e35f` is the same color as `#ee3355ff`.

If no alpha value is defined, it defaults to `ff` (opaque, no transparency). If alpha is set to `00`, the color is fully transparent.

**Comment by NilsJacobsen** [comment]
Current styling approach (subject to be improved)

1. Comes with default light styling and can be used ootb
2. For adjusting primary or a different primitive color, you can pass in a 500 color, and it calculates the other shades. (1-2 lines of css)
3. For specifc input field background hover states, … u can use shoelace's custom css properties. (5 - 10 lines of css)
4. If you have a complex token mapping based on components use the part api (10 - 30 lines of css)

Prop: If you don't have a complex system, it is super easy to use with almost no thoughts wasted on styling.

Cons: Complex Token Apis requires more complex mappings, see VS-Code. But for now this should be fine.

**Comment by felixhaeberle** [comment]
Yes, the approach is very powerful yet very simple for now 👍 good job
