### ISSUE TITLE
settings component save float doesn't appear after first edit / on attempt to second edit

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-ui-components#20]
### Context

Watch the LOOM
[https://www.loom.com/share/00c33786e112470eb6396eb8a11bdd42](https://www.loom.com/share/00c33786e112470eb6396eb8a11bdd42)

### Proposal

Fix the appearance of the float

**Comment by NilsJacobsen** [comment]
Duplicate [INLMC-13](https://linear.app/opral/issue/INLMC-13/the-floating-does-not-appear-if-i-change-something-a-second-time)
