### ISSUE TITLE
Not able to style dropdown

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-ui-components#25]
We already pass out the part api for the dropdown options. But currently, there is no way of handling selected options.

**Comment by NilsJacobsen** [comment]
@felix.haeberle as discussed in our call

**Comment by NilsJacobsen** [comment]
Seems currently not possible because it is based on classes that we can not access in the shaddowRoot. Gonna open an issue in the shoelace repo.

**Comment by felixhaeberle** [comment]
Thank you for opening the issue. 🙏 I'll try to find a workaround.

**Comment by felixhaeberle** [comment]
Answered in the discussion on Shoelace. I explained our use case a bit more clear in order for them to provide more useful help.

**Comment by NilsJacobsen** [comment]
I'm gonna close this because I don't think we get an answer in the next few days. We both should get pinged when there is something new in gh.

**Comment by felixhaeberle** [comment]
@nils.jacobsen Would be cool if we have a better option to do this but rn the current workaround is also okayish, nothing to be too worried about.

**Comment by NilsJacobsen** [comment]
I agree. We'll wait for an answer:)
