### ISSUE TITLE
performance issue of settings component

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-ui-components#26]
### Context

The settings component can get really slow when a lot of editings are happening in a short time. My wild guess would be thats because of heavy computation in comparing states within the component because the rest of the UI stays responsive.

WATCH THE LOOM
[https://www.loom.com/share/edde23e20dd84d57a680d17ed15b159e](https://www.loom.com/share/edde23e20dd84d57a680d17ed15b159e)

### Proposal

Fix performance issues and debounce / throttle checks.

Side note: This performance strategy is especially crucial for bigger components like the message component which might get even more complex in comparing states.

**Comment by NilsJacobsen** [comment]
I see that shouldn't be the case. Let me try to fix that.

**Comment by NilsJacobsen** [comment]
Can you confirm that it always gets triggered when you save?

**Comment by NilsJacobsen** [comment]
I can reproduce it. Working on a fix @felix.haeberle

**Comment by NilsJacobsen** [comment]
The issue was caused by calling `this.requestUpdate()` on a component. Turns out this is bad practice. Be really cautious with this method.

**Comment by NilsJacobsen** [comment]
@felix.haeberle can you confirm that the issue is resolved?

**Comment by NilsJacobsen** [comment]
Reopened because issue is not completely gone.
