### ISSUE TITLE
Versioning of inlang components

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-ui-components#27]
@felix.haeberle @niklas.buchfink <br><br>Do you want to pin a major version of the settings component to lower the risk of bugs?

I'm gonna do a 1.0.0 today. so you can pin that when releasing.

**Comment by felixhaeberle** [comment]
@nils.jacobsen Great idea! Let's do this.

**Comment by NiklasBuchfink** [comment]
@nils.jacobsen I agree 👍

**Comment by NilsJacobsen** [comment]
I released the 1.0.0 you can start pinning

**Comment by NilsJacobsen** [comment]
Gonna close this, as we all agreed.
