### ISSUE TITLE
settings component is broken with those settings

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang-message-ui-components#33]
### Context

In Sherlock, the message component does not render with this settings.json

```
{
	"$schema": "https://inlang.com/schema/project-settings",
	"sourceLanguageTag": "en",
	"languageTags": ["en", "de"],
	"modules": [
		"./../../../source-code/plugins/i18next/dist/index.js",
		"./../../../source-code/message-lint-rules/emptyPattern/dist/index.js",
		"./../../../source-code/message-lint-rules/identicalPattern/dist/index.js",
		"./../../../source-code/message-lint-rules/missingTranslation/dist/index.js",
		"./../../../source-code/message-lint-rules/messageWithoutSource/dist/index.js"
	],
	"plugin.inlang.i18next": {
		"pathPattern": {
			"client-page": "./../../app/i18n/locales/{languageTag}/client-page.json",
			"footer": "./../../app/i18n/locales/{languageTag}/footer.json",
			"second-page": "./../../app/i18n/locales/{languageTag}/second-page.json",
			"translation": "./../../app/i18n/locales/{languageTag}/translation.json"
		}
	},
	"experimental": {
		"aliases": true
	}
}
```

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/2941ddeb-fbd9-486c-8199-db2f502ccdd9/bbd8ef66-58d7-431d-b19e-04981146ceb9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC8yOTQxZGRlYi1mYmQ5LTQ4NmMtODE5OS1kYjJmNTAyY2NkZDkvYmJkOGVmNjYtNThkNy00MzFkLWIxOWUtMDQ5ODExNDZjZWI5IiwiaWF0IjoxNzEyOTI4Nzg3LCJleHAiOjMzMjgzNDg4Nzg3fQ.0WDTbYER_pTD9djzyR81dxmvhtVjfwVvRmQ_-XtbHC0 " alt="Bildschirmfoto 2024-04-12 um 15.31.11.png" width="1278" height="1105" />

### Proposal

Find the root cause & fix it.

**Comment by NilsJacobsen** [comment]
Thanks for handing in, gonna test it.

**Comment by NilsJacobsen** [comment]
Which repo do you use for testing? @felix.haeberle

**Comment by NilsJacobsen** [comment]
@felix.haeberle it's because the project is broken. Without the project we can't access installed plugins and lint rules with leads to a ui that only can show you the generell settings. But we shouldn't render the lint rule levels when there are no lint rules.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/7da9546f-4af1-429d-948a-46a146687d2f/2a7485d7-3997-49e7-9df2-fa99b8360d2f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC83ZGE5NTQ2Zi00YWYxLTQyOWQtOTQ4YS00NmExNDY2ODdkMmYvMmE3NDg1ZDctMzk5Ny00OWU3LTlkZjItZmE5OWI4MzYwZDJmIiwiaWF0IjoxNzEyOTI5MzIxLCJleHAiOjMzMjgzNDg5MzIxfQ.PWUGeSX1UF-ki4vvg_NB1P7ItbEXH9AFKX4cq5mIEWA " alt="image.png" width="399" height="1267" />

**Comment by felixhaeberle** [comment]
It might be beneficial if we display the errors in the settings view aswell then to guide the user to fix their settings. <br><br>On the other hand, thats a bad UX if the settings component where I can also fuck up my settings can't give me the interface any longer because I have done something bad.<br><br>Can we decouple the component from this validation logic? I guess we should tackle this challenge in the validation milestone. It should not be the case that I can destroy my component after Save 😄

**Comment by NilsJacobsen** [comment]
This is not the validation logic. We basically render the schema and fill it with the json. If we don't have the schema as in the example, you don't get the form. The settings are not dependant on valid settings. But you only get settings for your plugin if you correctly installed it. That is part of the module management. So you cant distroy the component with changing stuff.

**Comment by NilsJacobsen** [comment]
> The settings component is depended on valid settings which are not there when the project has errors. The crux is that you can make them invalid through using the settings component, leaving you alone and you then have to jump into your file to make them valid again which is not good.

**This is not correct**

**Comment by felixhaeberle** [comment]
ooh ! Thank you for clarifying. In our call 2min ago I got it wrong!
