### ISSUE TITLE
Provide a way to react on unsaved changes in settings-component

### ISSUE THREAD

**Issue by NiklasBuchfink** [opral/inlang-message-ui-components#34]
### Context

An app might want to prevent users from moving away from the settings component with unsaved changes. (e.g. prevent closing a modal)
It might be possible to derive this information by tracking whether the float is visible, but there should be an event for this.

### Proposal

Is this possible to solve this with event emitting like an `hasUnsavedChanges` event?

**Comment by NilsJacobsen** [comment]
Good point.<br>@niklas.buchfink it doesn't feel like a event, though. I would see it more like a state. Unfortunately this is not something we can handle in the component and pass out. <br><br>Pro: A bit easier then manually comparing new and old settings<br><br>Cons: More events. Bigger API<br><br>Question:<br>You would still need to use a signal to store the status right?

**Comment by NilsJacobsen** [comment]
```
<inlang-settings
   on:set-settings{(newSettings) => {
      if(JSON.stringify(newSettings)!==JSON.stringify(settings())){
        setSettings(newSettings)
        setHasChanges(true)
      } else {
         setHasChanges(false)
      }
   }}
></inlang-settings>
```

vs>

```
<inlang-settings
   on:set-settings{(newSettings) => {
        setSettings(newSettings)
   }}
   on:set-has-unsaved-changes{(hasChanges) => {
      if(hasChanges){
        setHasChanges(true)
      } else {
         setHasChanges(false)
      }
   }}
></inlang-settings>
```

I feel like it's even more effort to handle to events what do you think @niklas.buchfink

**Comment by NiklasBuchfink** [comment]
It would be enough to request a state like "float is visible" (component has unsaved changes) when the user tries to close a modal.

**Comment by NilsJacobsen** [comment]
We can't request something. We can pass in props and react on events.

**Comment by NilsJacobsen** [comment]
Jep 👍

**Comment by NilsJacobsen** [comment]
I feel like we don't need this rn. Reopen if disagree.
