### ISSUE TITLE
Fix import of icons

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-ui-components#5]
When using shoelace the app needs to set a relative path to a the `dist` of shoelace. This requires to have shoelace installed, which is not the case for some apps.

Find a solution where the icons are directly usable from the `inlang-settings` package.

**Comment by samuelstroschein** [comment]
finding a possibility to use inline svg's would be best to ensure that the component works without network access

**Comment by NilsJacobsen** [comment]
You mean that app devs can pass in a svg? @samuel.stroschein

**Comment by samuelstroschein** [comment]
@nils.jacobsen no, that you use (if possible) inline svg's for the icons you need for the component. 

* you can't set a `dist` path in the component. you don't have access to the filesystem/server the app is served from.    
* alternatively, fetch the icons from a CDN. but that requires network access and stuff like the CDN not being blocked in china

**Comment by samuelstroschein** [comment]
i just read the shoelace docs. i assume that you want to use [https://shoelace.style/components/icon#icon-libraries](https://shoelace.style/components/icon#icon-libraries). this component does not seem to offer inline svg's. if you want to use the component, you need to use a CDN. if we run into network issue problems, we can migrate to inline svg's in the future

**Comment by NilsJacobsen** [comment]
Hmm, there is no big need to use the shoelace icons. We only need an x icon in the settings. We can just use an inline svg for that. In the message component, it might be different, but for now I think it is easier to have them inline.
