### ISSUE TITLE
Clarify collaboration between personas (message-component)

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-ui-components#56]
Because it wasn't that clear yesterday.

**Comment by jldec** [comment]
super helpful thanks - I left a comment in the video

> <img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/f5d3f1ed-4fb1-418a-aa83-09d188cef4d8/0cce3c0f-3a44-4d33-ba6c-2340f7643dce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9mNWQzZjFlZC00ZmIxLTQxOGEtYWE4My0wOWQxODhjZWY0ZDgvMGNjZTNjMGYtM2E0NC00ZDMzLWJhNmMtMjM0MGY3NjQzZGNlIiwiaWF0IjoxNzE1MDc5MDk0LCJleHAiOjMzMjg1NjM5MDk0fQ.w1cqElPoNMu_1eOGmWY_OJr57ojuh4N0r2KZnT6j164 " alt="Screenshot 2024-05-07 at 06.50.26.png" width="1170" height="638" />
