### ISSUE TITLE
Create `message-component` package

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-ui-components#58]
Setup a message-component package with a storybook-lit instance.

**Comment by samuelstroschein** [comment]
Can you name the pacakge like you will name the component? In my mind step one is `<inlang-message-bundle-editor>`

**Comment by NilsJacobsen** [comment]
You are right we should name it `message-bundle` instead of `message`. Do we really need editor?<br><br>**Package and component naming reasons:**<br>There are two use cases: 

1. You need to identify the name of the package in the monorepo and npm (naming it component makes sense to indicate what it is)
2. In code you now that it is a component but you want to know where it came from (inlang)

So for the settings component it is -> `@inlang/settings-component` and `<inlang-settings>`

For the new one -> `@inlang/message-bundle-component` and `<inlang-message-bundle>` (we could add editor if needed)

**Comment by samuelstroschein** [comment]
sounds good. `<inlang-message-bundle` is likely enough
