### ISSUE TITLE
How do we deal with lints in variants

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-ui-components#59]
Currently lints are connected to the single translation row (now called message), but in the future they should probably also be connected to variants.

**Comment by NilsJacobsen** [comment]
@jldec right now the lint reports can only be connected to messages not variants right? or am I wrong? When do you think this will be possible? Futuretopic?

**Comment by jldec** [comment]
I'm still unsure why we need to make variants first class entities in our domain model, instead of just treating them as a details of a message. 

I can see how inlang users might want to operate on a slice of messages in a subset of the locales (perhaps the default mode for fink)

I don't have a good intuition for why users would want to filter messages by variant, or even why they would do crud on a variant level instead of on message level.

 cc: @samuel.stroschein

**Comment by samuelstroschein** [comment]
Because apps want/need to CRUD operate on variants. I am coming from a relational line of thought here. As an app i want this:

```
project.query.variant.delete("28j8sj21-23ksk2s")  
```

The alternative would be this: 

* mixing variants with messages

```
project.query.message.deleteVariant("ksosksokfs")
```

**Comment by NilsJacobsen** [comment]
I made a mistake in my description: it is also variants not only.

**Comment by samuelstroschein** [comment]
It's a good question though how the user model unfolds. I know that some lints attach to a variant, some to a message, and some even to a message bundle. <br><br>Variant = Using wrong input or whatever<br>Message = "Wrong locale"<br>MessageBundle = "Missing locale"<br><br>It seems more intuitive to me to have a primitive for Variants. @loris.sigrist @martin.lysk1 @felix.haeberle @niklas.buchfink if you have an opinion pls let us know (if not, ignore)

**Comment by NilsJacobsen** [comment]
I discussed that with @martin.lysk1 today. I think we possibly want all 3 of them to indicate best what is wrong.

**Comment by NilsJacobsen** [comment]
Update: [https://www.loom.com/share/65e2345e278e4485a8051a11ec5f1e33?sid=04d0bf23-31ff-4ad7-8fcd-73ce84a3c633](https://www.loom.com/share/65e2345e278e4485a8051a11ec5f1e33?sid=04d0bf23-31ff-4ad7-8fcd-73ce84a3c633)<br><br>@jldec FYI

**Comment by samuelstroschein** [comment]
Okay, we need lint reports on variant, message, and message bundle level.

Thanks @nils.jacobsen for the loom, confirmed my assumptions. Also confirmed that we need ids for messages and variants to relate lint reports. As an example: 

```
report({ body: "xyzw", messageId: "blalba" })

// or

report({ body: "xyzw", variantId: "blalba" })
```

**Comment by jldec** [comment]
ref [MESDK-132](https://linear.app/opral/issue/MESDK-132/ids-to-reference-messages-and-variants)
