### ISSUE TITLE
Allow markdown for settings description & examples

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang-message-ui-components#9]
The description should be able to render markdown elements like links, bold, or inline code.

**Comment by NilsJacobsen** [comment]
Same applies for the example array.

**Comment by samuelstroschein** [comment]
Changed the title. Markdown ≠ rich text

**Comment by samuelstroschein** [comment]
@nils.jacobsen is markdown required? the JSON schema spec does not seem to contain info about markdown. Introducing markdown would likely break interop.

**Comment by NilsJacobsen** [comment]
It would make the settings better. 

**Example:**
VS-Code is also having it to link to stuff in the description.

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/c8ce253f-4899-4abb-ab9c-6fa5b3050f27/8f448946-82d8-480d-bfcc-9e641e5cb6b7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC9jOGNlMjUzZi00ODk5LTRhYmItYWI5Yy02ZmE1YjMwNTBmMjcvOGY0NDg5NDYtODJkOC00ODBkLWJmY2MtOWU2NDFlNWNiNmI3IiwiaWF0IjoxNzEyNTU5OTczLCJleHAiOjMzMjgzMTE5OTczfQ.HdVr9T4b7am5UJd5tzn_FjO_SMsDzx5WrAOKCM61f2k " alt="image.png" width="1077" height="340" />


I though we can use the description to store markdown as a string, 'cause technically it is a description. I actually only need inline markdown. In which case it would break interop? Not sure if I can follow?

**Comment by NilsJacobsen** [comment]
I styled the examples as a list ([INLMC-39](https://linear.app/opral/issue/INLMC-39/style-examples-to-be-a-list-not-a-string)), so we don't need this kind of flexibility for them. The only important thing is the links in the description now. This will not be part of the releasable milestone so let's wait until the app builders come up with that requirement.

**Comment by NilsJacobsen** [comment]
I see. Thanks for sharing.
